apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webhosting
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  tls:
  - hosts:
      - dev.kubeguide.com
    secretName:  secret-tls
  ingressClassName: nginx
  rules:
    - host: dev.kubeguide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-fr-service
                port:
                  number: 80
          - path: /rest/api/v1
            pathType: Prefix
            backend:
              service:
                name: webapp-backend-service
                port:
                  number: 80
