name: Docker Image CI

on:
  push:
    branches:
      - 'develop'

jobs:
  # define job to build and publish docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build   webapp  image
        run:  docker  build   ./webapp -t zamiramiri5/kubernetesguide-webapp:develop
      - name: Push    webapp  image
        run:  docker  push    zamiramiri5/kubernetesguide-webapp:develop
      - name: Build   webapp-backend  image
        run:  docker  build   ./webapp-backend -t zamiramiri5/kubernetesguide-webapp-backend:develop
      - name: Push    webapp-backend  image
        run:  docker  push    zamiramiri5/kubernetesguide-webapp-backend:develop

