name: Docker Image CI

on:
  push:
    branches:
      - 'develop'

jobs:
  # define job to build and publish docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build nodeJs image
        run: docker build ./webapp -t zamiramiri5/kubernetesguide-webapp:develop
      - name: Push image
        run: docker push zamiramiri5/kubernetesguide-webapp:develop
